[env:esp8266]
platform = espressif8266
board = nodemcuv2
framework = arduino

monitor_speed = 115200
upload_speed = 921600
upload_port = COM3
monitor_port = COM3

lib_deps = 
    paulstoffregen/OneWire
    milesburton/DallasTemperature
    arduino-libraries/ArduinoMqttClient@^0.1.8
    knolleary/PubSubClient@^2.8
    bblanchon/ArduinoJson@^7.2.2