[env:esp32-c6-devkitc-1]
platform = https://github.com/pioarduino/platform-espressif32/releases/download/54.03.20/platform-espressif32.zip
board = esp32-c6-devkitc-1
framework = arduino 

build_flags =
    -DARDUINO_USB_CDC_ON_BOOT=0
    -DARDUINO_USB_MODE=0

monitor_speed = 115200
upload_speed = 921600
; upload_port = COM6
; monitor_port = COM6

lib_deps = 
    paulstoffregen/OneWire
    milesburton/DallasTemperature
    arduino-libraries/ArduinoMqttClient@^0.1.8
    knolleary/PubSubClient@^2.8
    bblanchon/ArduinoJson@^7.2.2
    